import { Layout, SignUp } from '@/modules';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function RegisterPage() {
	return (
		<>
			<Head>
				<title>Register user</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${inter.className}`}>
				<Layout>
					<SignUp />
				</Layout>
			</main>
		</>
	);
}
