import { Layout, User } from '@/modules';
import { authOptions } from '@/utils';
import type { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import { getServerSession, type Session } from 'next-auth';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

const UserPage = (props: InferGetServerSidePropsType<typeof getServerSideProps>) => {
	return (
		<>
			<Head>
				<title>User page</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${inter.className}`}>
				<Layout>
					<User {...props} />
				</Layout>
			</main>
		</>
	);
};

export const getServerSideProps: GetServerSideProps<{ session: Session }> = async (context) => {
	const session = await getServerSession(context.req, context.res, authOptions);

	if (!session) {
		return {
			redirect: {
				destination: '/',
				permanent: false,
			},
		};
	}

	return {
		props: {
			session,
		},
	};
};

export default UserPage;
